### ISSUE TITLE
MAIN: Create the footer

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#31]
<img width="953" alt="Screen Shot 2020-07-23 at 8 58 54 AM" src="https://user-images.githubusercontent.com/8326985/88256034-c2ac1280-ccc2-11ea-93ce-12bcfa1d214a.png">

**Create the footer with placeholders** 
4 columns : About PandAid, Partners, Resources, Contacts with mock links

**Follow design guide:** https://www.figma.com/file/a8zZGZXslthCfmXEPH2kak/%F0%9F%92%8AHospitalrun---Map?node-id=351%3A0

**Comment by SerejaSerjik** [comment]
https://github.com/hospitalrun-ua/frontend/pull/59
