### ISSUE TITLE
FORM : Registration for volunteers

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#34]
<img width="670" alt="Screen Shot 2020-07-23 at 8 56 52 AM" src="https://user-images.githubusercontent.com/8326985/88255940-78c32c80-ccc2-11ea-8cbf-d9ff107e92b1.png">

**Registration for volunteers** 
The window which contains such information:
Name, Surname, city, number, type of help and photo

Fill with placeholders and mock data

Design guide: 
https://www.figma.com/file/a8zZGZXslthCfmXEPH2kak/%F0%9F%92%8AHospitalrun---Map?node-id=351%3A0

**Comment by Thealoner** [comment]
PR: https://github.com/hospitalrun-ua/frontend/pull/61
