### ISSUE TITLE
FORM: Registration form for organization 

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#38]
<img width="436" alt="Screen Shot 2020-07-23 at 10 02 43 AM" src="https://user-images.githubusercontent.com/8326985/88259784-ac568480-cccb-11ea-94d1-aeb2e5133cc8.png">

Similar  form to Volunteers, just replace "Volunteers" with "Organization

We need now just UX implementation with mock data

The form appears after the user press a button " Долучитись як організація"

**Comment by Thealoner** [comment]
PR: https://github.com/hospitalrun-ua/frontend/pull/61
