### ISSUE TITLE
TABLE: Status column with colors 

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#39]
<img width="110" alt="Screen Shot 2020-07-23 at 10 10 04 AM" src="https://user-images.githubusercontent.com/8326985/88260328-d197c280-cccc-11ea-8c60-0413104b5b38.png">
Status column items should refer status with color - add component background such us - new (green), in progress( yellow) and done( red)

**Comment by minahabibm** [comment]
can I get assigned?

**Comment by tomkaX** [comment]
Sure! Please go ahead!

**Comment by minahabibm** [comment]
just making sure I found the status bar on the applications page. there are On hold/  in Progress / Received / Closed. if this is correct pending supposed to stay the same? and what the colors for each of these?

**Comment by tomkaX** [comment]
On hold - yellow  #FFB946;
 in Progress -   green background: #0B9785;
 Received - red #F7685B;
 Closed - blue #1540A4;

**Comment by minahabibm** [comment]
I added the feature. do you need it to be more dynamic or just for x.value for now?

**Comment by tomkaX** [comment]
Вітаю з викоаннням першого завдання!
Підтверди будь ласка інвайт долучитись до PandAid
