### ISSUE TITLE
RegExp for phone numbers 

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#45]
All phone numbers should be in valid international form with + sign in beginning 

need to create regexp to check the registration form for the valid phone number ( 11 digits and + sign)

**Comment by tomkaX** [comment]
<img width="1360" alt="Screen Shot 2020-07-23 at 8 45 55 PM" src="https://user-images.githubusercontent.com/8326985/88319973-95dd1700-cd25-11ea-9388-dece37abea05.png">
Вже  є імплементована форма - можеш додати перквірку туди?

**Comment by lutogin** [comment]
Я бекендер, не фронт

**Comment by tomkaX** [comment]
так я зрозуміла - а чи можеш скинути де саме код, бо не знайшла в пул реквестах

**Comment by FreeNikita** [comment]
@tomkaX Эту таску еще не закрыли ?

**Comment by Varkh** [comment]
PR is in backend
https://github.com/hospitalrun-ua/pandaid/pull/37
