### ISSUE TITLE
HEADER: modify search component 

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#47]
Search component should looks like : 
<img width="466" alt="Screen Shot 2020-07-23 at 1 07 36 PM" src="https://user-images.githubusercontent.com/8326985/88275169-96ee5400-cce5-11ea-9de4-1a635d4aace7.png">

In Current implementation :
<img width="231" alt="Screen Shot 2020-07-23 at 1 08 38 PM" src="https://user-images.githubusercontent.com/8326985/88275228-b1283200-cce5-11ea-8136-255583426745.png">

Change component width, font color and add search icon in beginning

**Comment by lenadgit** [comment]
how to assign?

**Comment by lenadgit** [comment]
done https://github.com/hospitalrun-ua/frontend/pull/62

**Comment by lenadgit** [comment]
Merged 
https://github.com/hospitalrun-ua/frontend/pull/62
https://github.com/hospitalrun-ua/frontend/pull/56
