### ISSUE TITLE
Footer : change twitter icon to github svg 

### ISSUE THREAD

**Issue by tomkaX** [hospitalrun-ua/frontend#77]
<img width="327" alt="Screen Shot 2020-07-30 at 11 35 12 AM" src="https://user-images.githubusercontent.com/8326985/88900905-c3abe980-d258-11ea-9aa6-be208bb5e15d.png">

We not use twitter for now - nut need to add GitHub icon instead

**Comment by GovindKurapati** [comment]
I've replaced twitter icon with github icon.

**Comment by tomkaX** [comment]
<img width="351" alt="Screen Shot 2020-07-31 at 10 35 11 AM" src="https://user-images.githubusercontent.com/8326985/89011742-8f4c3200-d319-11ea-8227-ba40932aeafa.png">
issue should update svg path of github icon as well - now fixed

https://github.com/simple-icons/simple-icons/blame/develop/icons/github.svg
